### ISSUE TITLE
Ellipses (...) don't work

### ISSUE THREAD

**Issue by nicolasr75** [andreasbm/lit-translate#11]
I noticed that because of the special meaning of the dot as the separator it is not possible to use ellipses in strings. A typical example would be "The page is being loaded...". I used a quick fix to make this work for me by changing the code in helper.js as follows:

```
export function lookup(key, config) {
    //Escape ellipses
    const escapedKey = key.replace("...", "###");
	
    // Split the key in parts (example: hello.world)	
    const parts = escapedKey.split(".").map(p => p.replace("###", "..."));
    ...
```
Probably not the nicest solution but it works for me. I thought about cases where the string to translate contains two sentences, f.e. "The data have been successfully saved. Please reload the page!". This would still be distinguishable from the separator because of the space after the dot. I don't know what you think but maybe you want to consider some of these cases in a later version.

Thanks for the great work!
Nicolas

**Comment by andreasbm** [comment]
Thanks for opening this issue!

In order to help you further I would love to see a code example of how you are using the library. It should definitely be possible to use dots in your strings without any issues.

First you need to define your translations as a JSON structure like this.
```json
// en.json
{
  "messages": {
    "loading": "The page is being loaded..."
  }
}
```

The next step is to use the `registerTranslateConfig` function to register a loader that loads and parses the translations based on a language identifier. After that you can call the `use` function with the language identifier. This will load the file with the translations.

```js
import { registerTranslateConfig, use } from "lit-translate";

registerTranslateConfig({
  loader: lang => fetch(`/path/to/translations/${lang}.json`).then(res => res.json())
});

use("en");
```

Now you can translate text by referring to the path of the JSON structure of the translations.

```js
import { get } from "lit-translate";

get("messages.loading"); // Will return "The page is being loaded..."
```

I have created a codepen that demonstrates how https://codepen.io/andreasbm/pen/NWqbzed?editors=1010.

**Comment by nicolasr75** [comment]
Hello Andreas and thanks for the detailed explanation. I followed all that according to your Github readme and all that works as expected except for this use case:

I like having the full english text as the key. The famous GNU GetText works like this. There you would, f.e. have source code like:

    ShowMessage(_("The page is being loaded..."));

Where the '_(...)' is a special function but the name can actually be configured. The GNU GetText tools then search for the occurrence of this function and take the entire argument as the key for the translation. It has three great properties: 1- you don't need a separate english translation because the english translations are your keys. 2 - the tools can automate the extraction of the keys from source. 3 - the code is perfectly understandable because you don't shorten the english translation to key words.

I understand that your implementation is meant to work with rather short key words. I used that approach with other systems and personally like the GetText approach much more.

Given that, I actually could  use your implementation for that if it were not for the problem with the dots. The key is not allowed to have dots as regular text, that's the actual issue! The code fix I suggested is enough for me but I thought other people might experience the same issue.

**Comment by andreasbm** [comment]
Thanks for your thorough description of the issue 👍 I understand why you prefer the approach of using English strings as keys. If you take this approach with `lit-translate`, I recommend overwriting the `lookup` and `empty` hooks using the `registerTranslateConfig` function like this.

```js
import { registerTranslateConfig, use, get } from "lit-translate";

registerTranslateConfig({
  lookup: (key, config) => config.strings != null ? config.strings[key] : key,
  empty: key => key,
  loader: lang => {
    switch (lang) {
      case "da":
        return {
          "The page is being loaded...": "Siden indlæses..."
        };
    }
  }
});

use("en");
get("The page is being loaded..."); // Will return "The page is being loaded..."

use("da");
get("The page is being loaded..."); // Will return "Siden indlæses..."
```

I cooked up a Codepen with the code above [here](https://codepen.io/andreasbm/pen/RwPompd?editors=1010).

Due to the extensibility of `lit-translate`, I would prefer to keep the library as it is right now. I do however think it is a really good idea to add a section to the readme explaining various use-cases such as the one you describe 🌞

**Comment by andreasbm** [comment]
I added [this](https://github.com/andreasbm/lit-translate#using-the-default-translations-as-keys) section to the readme to clear things up for other people in the future. Thanks for opening the issue, I will close it for now 👍
